// === Бронирование через WhatsApp Ули ===
// Гость кликает «Я беру» → открывается чат в WhatsApp с готовым сообщением.
// Бесплатные облачные «бины» без регистрации не дают браузеру писать (CORS),
// поэтому делаем самый простой и надёжный путь — прямое сообщение.
const WHATSAPP_PHONE = '79697096595';

// === Большие хочулики ===
const WISHES = [
  {
    id: 'kisses',
    title: 'Поцелуи в щёчку',
    subtitle: 'без счёта',
    note: 'Сколько хош!',
    type: 'sweet',
    image: 'assets/kisses.jpg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'stories',
    title: 'Сторис обо мне',
    subtitle: 'с нашей фотой',
    note: 'Выложи нашу фотку и подпиши: «Кайфуля самая любимая подружка!»',
    type: 'social',
    image: 'assets/stories.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'spider-robot',
    title: 'Танец робота-паука!',
    subtitle: 'я хочу его увидеть',
    note: 'Дополнительно начислю очки уважения!',
    type: 'sweet',
    image: 'assets/spider-robot.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'botsad',
    title: 'Сводить меня в Ботанический сад',
    subtitle: '',
    note: 'Я очень давно там не была...',
    type: 'experience',
    image: 'assets/botsad.svg',
    reservable: true,
    favorite: true,
  },
  {
    id: 'cap',
    title: 'Кепка «кайфуля»',
    subtitle: 'травяного цвета · с вышивкой',
    note: 'Очень хочу кепку травяного цвета с вышивкой «кайфуля!»',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/cap.svg',
    reservable: true,
    favorite: true,
  },

  // === По вашему желанию ===
  {
    id: 'reab',
    title: 'Сбор на лечение',
    subtitle: 'Собираю деньги на реабилитацию',
    note: 'Я раздробила себе два позвонка и сломала все кости в организме. Восстановилась, но до сих пор хромаю.',
    type: 'collect',
    target: 30000,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://bubnovsky.org/spb/prices/',
    image: 'assets/reab.jpg',
    reservable: false,
  },
  {
    id: 'cape',
    title: 'Кейп с капюшоном',
    subtitle: 'VintageDresses · сбор',
    note: 'Накидка вместо пальто, с фибулой и большим капюшоном. Как будто из другого века.',
    type: 'collect',
    target: 28000,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://vintagedresses.ru/o/b99ab9/',
    image: 'assets/cape.jpg',
    reservable: false,
  },
  {
    id: 'coat',
    title: 'Пальто-трапеция',
    subtitle: 'Primula Design · зелёное · сбор',
    note: 'Шерсть с подкладом, зелёного. Хочу одно настоящее пальто, чтобы носить годами.',
    type: 'collect',
    target: 37500,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://primuladesign.ru/shop/palto-trapeciia-v-zelenom-cvete',
    image: 'assets/coat.jpg',
    reservable: false,
  },
  {
    id: 'spf',
    title: 'Солнцезащитный стик',
    subtitle: 'TOCOBO · SPF50+ · сколько угодно',
    note: 'Рак кожи — отстой.',
    type: 'sweet',
    price: null,
    link: 'https://www.wildberries.ru/catalog/160847016/detail.aspx?size=267320337',
    image: 'assets/spf.webp',
    reservable: false,
  },
  {
    id: 'feathers',
    title: 'Перья в волосы',
    subtitle: 'PtashkaHair · 20–25 см · М',
    note: 'Натуральные, широкие. Без брони — пусть будет много, в волосах много места.',
    type: 'sweet',
    price: null,
    link: 'https://www.wildberries.ru/catalog/189472337/detail.aspx?size=310137221',
    image: 'assets/feathers.webp',
    reservable: false,
  },
  {
    id: 'quoridor',
    title: 'Настольная игра «Коридор»',
    subtitle: 'Стиль Жизни · мини · 8+',
    note: 'Стратегия для вечеров с Лёшей.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/123438701/detail.aspx?size=216966915',
    image: 'assets/quoridor.webp',
    reservable: true,
  },
  {
    id: 'plates',
    title: 'Тарелки с ежиками',
    subtitle: 'Lefard · 20,5 см · 2 шт · фарфор',
    note: 'Хочу красивую посуду — даже когда ем одна.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/884134513/detail.aspx?size=1333921861',
    image: 'assets/plates.webp',
    reservable: true,
  },
  {
    id: 'blouse-para',
    title: 'Блузка нарядная оверсайз',
    subtitle: 'PARA SLOW',
    note: '',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/229050850/detail.aspx?size=362017336',
    image: 'assets/blouse-para.webp',
    reservable: true,
  },
  {
    id: 'litres',
    title: 'Подписка Литрес или Я.Книги',
    subtitle: 'на год',
    note: 'Обожаю читать! Это мой самый любимый способ избегания реальности!',
    type: 'gift',
    price: '~3 500 ₽',
    link: null,
    image: 'assets/litres.svg',
    reservable: true,
  },
  {
    id: 'shades',
    title: 'Тёмные очки',
    subtitle: 'с коричневой оправой',
    note: 'От ультрафиолета.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/shades.svg',
    reservable: true,
  },
  {
    id: 'rope-park',
    title: 'Билет в верёвочный парк',
    subtitle: '',
    note: 'Белки живут на деревьях.',
    type: 'experience',
    price: null,
    link: null,
    image: 'assets/rope-park.svg',
    reservable: true,
  },
];

// === Маленькие хочулики — короткие, без картинок ===
const SMALL_WISHES = [
  { id: 'sm-1', title: 'Завтрак в кровать', subtitle: 'с сырниками', reservable: true },
  { id: 'sm-2', title: 'Букет полевых цветов', subtitle: 'не магазинных', reservable: true },
  { id: 'sm-3', title: 'Свеча с запахом дождя', subtitle: '', reservable: true },
  { id: 'sm-4', title: 'Сертификат на массаж спины', subtitle: '', reservable: true },
  { id: 'sm-5', title: 'Кашемировые носки', subtitle: 'тёплые', reservable: true },
  { id: 'sm-6', title: 'Свежий батон с маслом', subtitle: 'и солью', reservable: true },
  { id: 'sm-7', title: 'Открытка от руки', subtitle: 'обычной почтой', reservable: true },
  { id: 'sm-8', title: 'Прогулка по крышам', subtitle: 'белые ночи', reservable: true },
  { id: 'sm-9', title: 'Билет на сапбординг', subtitle: 'по каналам', reservable: true },
  { id: 'sm-10', title: 'Сертификат в книжный', subtitle: '', reservable: true },
  { id: 'sm-11', title: 'Парфюм с инжиром', subtitle: '', reservable: true },
  { id: 'sm-12', title: 'Большая мягкая толстовка', subtitle: 'оверсайз', reservable: true },
  { id: 'sm-13', title: 'Конфеты-марципаны', subtitle: 'фигурные', reservable: true },
  { id: 'sm-14', title: 'Маска для лица в баночке', subtitle: '', reservable: true },
  { id: 'sm-15', title: 'Кофе с подругой в новом месте', subtitle: '', reservable: true },
];
