// === Бронирование через jsonblob.com ===
// Без регистрации. ID сгенерирован один раз — менять не надо.
const BLOB_URL = 'https://jsonblob.com/api/jsonBlob/019e30d9-7aa3-736c-bac8-1b96d56162cc';

// === Список желаний ===
// type: 'gift' | 'collect' | 'experience' | 'sweet' | 'social'
// reservable: можно ли забронировать. false — без брони, сколько угодно.

const WISHES = [
  {
    id: 'kisses',
    title: 'Поцелуи в щёчку',
    subtitle: 'без счёта',
    note: 'От тебя лично. Сколько хочешь — всё засчитается.',
    type: 'sweet',
    image: 'assets/kisses.jpg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'stories',
    title: 'Сторис обо мне',
    subtitle: 'с нашей фотой',
    note: 'Выложи в сторис нашу фотку и подпиши: «Кайфуля самая любимая подружка!». Так я заплачу.',
    type: 'social',
    image: 'assets/stories.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'tattoo',
    title: 'Тату «Люблю Улю»',
    subtitle: 'без ограничений',
    note: 'Это прикол. Если кто-то реально сделает — обещаю плакать. Сколько угодно желающих.',
    type: 'sweet',
    image: 'assets/tattoo.svg',
    reservable: false,
    favorite: true,
  },
  {
    id: 'feathers',
    title: 'Перья в волосы',
    subtitle: 'PtashkaHair · 20–25 см · М',
    note: 'Натуральные, широкие. Без брони — пусть будет много, в волосах много места.',
    type: 'sweet',
    price: null,
    link: 'https://www.wildberries.ru/catalog/189472337/detail.aspx?size=310137221',
    image: 'assets/feathers.webp',
    reservable: false,
  },
  {
    id: 'reab',
    title: 'Реабилитация в центре Бубновского',
    subtitle: 'сбор',
    note: 'У меня раздроблено два позвонка. Я восстановилась, но всё равно хромаю при ходьбе. Пора заняться здоровьем.',
    type: 'collect',
    target: 30000,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://bubnovsky.org/spb/prices/',
    image: 'assets/reab.svg',
    reservable: false,
  },
  {
    id: 'cape',
    title: 'Кейп с капюшоном',
    subtitle: 'VintageDresses · сбор',
    note: 'Накидка вместо пальто, с фибулой и большим капюшоном. Как будто из другого века.',
    type: 'collect',
    target: 28000,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://vintagedresses.ru/o/b99ab9/',
    image: 'assets/cape.jpg',
    reservable: false,
  },
  {
    id: 'coat',
    title: 'Пальто-трапеция',
    subtitle: 'Primula Design · зелёное · сбор',
    note: 'Шерсть с подкладом, зелёного. Хочу одно настоящее пальто, чтобы носить годами.',
    type: 'collect',
    target: 37500,
    raised: 0,
    payment: { method: 'Тинькофф', value: '+7 969 709 65 95' },
    link: 'https://primuladesign.ru/shop/palto-trapeciia-v-zelenom-cvete',
    image: 'assets/coat.jpg',
    reservable: false,
  },
  {
    id: 'cap',
    title: 'Кепка «кайфуля»',
    subtitle: 'травяного цвета',
    note: 'С надписью «кайфуля». Зелёная, как трава во дворе на Петроградке.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/cap.svg',
    reservable: true,
  },
  {
    id: 'spf',
    title: 'Солнцезащитный стик',
    subtitle: 'TOCOBO · SPF50+',
    note: 'Рак кожи — отстой. Хочу мазаться нормально каждый день.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/160847016/detail.aspx?size=267320337',
    image: 'assets/spf.webp',
    reservable: true,
  },
  {
    id: 'quoridor',
    title: 'Настольная игра «Коридор»',
    subtitle: 'Стиль Жизни · мини · 8+',
    note: 'Стратегия для вечеров с Лёшей. Мини-версия — удобно брать с собой.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/123438701/detail.aspx?size=216966915',
    image: 'assets/quoridor.webp',
    reservable: true,
  },
  {
    id: 'plates',
    title: 'Тарелки с ежиками',
    subtitle: 'Lefard · 20,5 см · 2 шт · фарфор',
    note: 'Хочу красивую посуду — даже когда ем одна.',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/884134513/detail.aspx?size=1333921861',
    image: 'assets/plates.webp',
    reservable: true,
  },
  {
    id: 'blouse-para',
    title: 'Блузка нарядная оверсайз',
    subtitle: 'PARA SLOW',
    note: '',
    type: 'gift',
    price: null,
    link: 'https://www.wildberries.ru/catalog/229050850/detail.aspx?size=362017336',
    image: 'assets/blouse-para.webp',
    reservable: true,
  },
  {
    id: 'litres',
    title: 'Подписка Литрес или Я.Книги',
    subtitle: 'на год',
    note: 'Хочу читать без ограничений. Любой из двух — на твой вкус.',
    type: 'gift',
    price: '~3 500 ₽',
    link: null,
    image: 'assets/litres.svg',
    reservable: true,
  },
  {
    id: 'shades',
    title: 'Тёмные очки',
    subtitle: '',
    note: 'Большие, тёмные, как у героинь шестидесятых.',
    type: 'gift',
    price: null,
    link: null,
    image: 'assets/shades.svg',
    reservable: true,
  },
  {
    id: 'rope-park',
    title: 'Билет в верёвочный парк',
    subtitle: '',
    note: 'Хочу высоту, страх и победу за один день.',
    type: 'experience',
    price: null,
    link: null,
    image: 'assets/rope-park.svg',
    reservable: true,
  },
];
